"""Standalone Smart Place WebSocket client library.

Has no homeassistant dependency; safe to import from a notebook or CLI.
The HA integration in custom_components/smart_place/ is a thin wrapper.
"""

from .client import (
    CapturedFrame,
    DisconnectCallback,
    ExponentialBackoff,
    FrameHandler,
    ReauthCallback,
    SmartPlaceClient,
    install_token_redaction_filter,
)
from .commands import KNOWN_COMMANDS, CommandDefinition, Commands
from .messages import KNOWN_MESSAGES, parse_frame
from .protocol import (
    DISCOVERY_ORIGIN,
    GlobalConfig,
    GoToLinkSSL,
    MessageDefinition,
    NamedFields,
    NamedValue,
    ProtocolError,
    ServerFrame,
    SessionPhase,
    SessionState,
    SmartPlaceAuthError,
    SmartPlaceOfflineError,
    Temperature,
    UnknownFrame,
    encode_frame,
    parse_chart_references,
    parse_unit_hints,
    repair_mojibake,
)
from .state import (
    CHART_RANGE_SERIES_HIGH_TARIFF,
    CHART_RANGE_SERIES_LOW_TARIFF,
    CHART_RANGE_SERIES_TOTAL,
    ChartReading,
    SmartPlaceState,
    chart_target_status,
)
from .tariff import (
    TARIFFS,
    TariffYear,
    energy_cost_chf,
    is_high_tariff,
    next_tariff_boundary,
    price_chf_per_kwh,
    rates_for,
    today_range_epochs,
)

__all__ = [
    "CHART_RANGE_SERIES_HIGH_TARIFF",
    "CHART_RANGE_SERIES_LOW_TARIFF",
    "CHART_RANGE_SERIES_TOTAL",
    "DISCOVERY_ORIGIN",
    "KNOWN_COMMANDS",
    "KNOWN_MESSAGES",
    "TARIFFS",
    "CapturedFrame",
    "ChartReading",
    "CommandDefinition",
    "Commands",
    "DisconnectCallback",
    "ExponentialBackoff",
    "FrameHandler",
    "GlobalConfig",
    "GoToLinkSSL",
    "MessageDefinition",
    "NamedFields",
    "NamedValue",
    "ProtocolError",
    "ReauthCallback",
    "ServerFrame",
    "SessionPhase",
    "SessionState",
    "SmartPlaceAuthError",
    "SmartPlaceClient",
    "SmartPlaceOfflineError",
    "SmartPlaceState",
    "TariffYear",
    "Temperature",
    "UnknownFrame",
    "chart_target_status",
    "encode_frame",
    "energy_cost_chf",
    "install_token_redaction_filter",
    "is_high_tariff",
    "next_tariff_boundary",
    "parse_chart_references",
    "parse_frame",
    "parse_unit_hints",
    "price_chf_per_kwh",
    "rates_for",
    "repair_mojibake",
    "today_range_epochs",
]
